In [1]:
from Convolutional_Network import conv_net
import FinanceDataManager
import Preprocessing

import numpy as np
from keras.models import Sequential
from keras.layers.core import Activation, Dense, Flatten
from keras.optimizers import SGD
import matplotlib.pyplot as plt
from keras.layers.convolutional import  Conv1D, MaxPooling1D

Using TensorFlow backend.


In [27]:
data_manager = FinanceDataManager.FinanceDataManager()
data = data_manager.get_prices(stock_name="AAPL", start = "2010-01-01", end = "2010-01-08")
window_size=20
data.shape

(5,)

In [28]:
data2 = np.atleast_2d(data)
data2.shape

(1, 5)

In [14]:
asd = np.array([1,2,3,4,5])
asd

array([1, 2, 3, 4, 5])

In [22]:
asd2 = np.atleast_2d(asd)
asd2

array([[1, 2, 3, 4, 5]])

In [24]:
asd3 = asd2.T
asd3

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [26]:
asd4 = np.asarray(asd3)
asd4

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [30]:
range(0, asd4.shape[0] - window_size)

range(0, -15)

In [32]:
asd5 = np.array([asd4[start:start + window_size] for start in range(0, asd4.shape[0] - window_size)])

In [34]:
np.atleast_3d(asd5)
asd5

array([], dtype=float64)